# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Aditya Devarakonda
author: Aditya Devarakonda
email: 
location: 584F Soda Hall
  Berkeley, CA 94720
description: > # this means to ignore newlines until "baseurl:"
  I am a 5th year Ph.D. student advised by Jim Demmel and Michael W. Mahoney.
  I work on the design of communication-avoiding algorithms for numerical linear algebra and machine learning.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
linkedin_username: adevarakonda
github_username:  aditya08
gscholar_username: 

# Build settings
markdown: kramdown
#theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
