baseURL = "https://aditya08.github.io/"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Aditya Devarakonda"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = false

[frontmatter]
lastmod = ["lastmod", ":fileModTime", ":default"]

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[params]
title = "Aditya Devarakonda"
author = "Aditya Devarakonda"
copyright = "2021"
description = "Assistant Professor at Wake Forest University\n\naditya 'at' wfu.edu\n Manchester Hall"
profilePicture = "images/profile.jpg"
keywords = ""
favicon = "favicons/"
# example ["css/custom.css"]
customCss = []
# example ["js/custom.js"]
customJs = [] 
mainSections = ["post"]
images = ["images/site-feature-image.png"]
doNotLoadAnimations = true
# Form Spree Contact Form
#contactFormAction = "https://formspree.io/f/your-form-hash-here"
# Google Site Verify
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
indexDateFormat = "Mon, Jan 2, 2006"
listDateFormat = "Jan 2"
singleDateFormat = "Mon, Jan 2, 2006"
# Commento Comments
# CommentoURL = "https://commento.example.com/js/commento.js"
# Read More links for truncated summaries
# readMore = true
# postSectionName = "blog"

[params.simpleAnalytics]
# enable = true
# customurl = "https://analytics.example.com"

## Math settings
[params.math]
enable = true  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
#[[params.socialIcons]]
#icon = "fab fa-linkedin"
#title = "Linkedin"
#url = "https://de.linkedin.com/"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/aditya08/"

[[params.socialIcons]]
icon = "ai ai-google-scholar"
title = "GoogleScholar"
url = "https://scholar.google.com/citations?user=Ao-FJHwAAAAJ&hl=en"

#[[params.socialIcons]]
#icon = "fas fa-envelope"
#title = "e-mail"
#url = "mailto:mail@example.com"

[[params.socialIcons]]
icon = "ai ai-cv"
title = "CV"
url = "../data/aditya_cv.pdf"

[[params.socialIcons]]
icon = "ai ai-orcid"
title = "ORCID"
url = "https://orcid.org/0000-0002-8251-9150"

[markup.goldmark.renderer]
unsafe= true

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "About"
  weight = 200
  identifier = "about"
  url = "/about/"

  [[menu.main]]
  name = "Teaching"
  weight = 300
  identifier = "Teaching"
  url = "/teaching/"

  [[menu.main]]
  name = "Research"
  weight = 400
  identifier = "research"
  url = "/research/"


    [[menu.main]]
  name = "Publications"
  weight = 500
  identifier = "publications"
  url = "/publications/"


  #[[menu.main]]
  #name = "Posts"
  #weight = 600
  #identifier = "posts"
  #url = "/post/"